### ISSUE TITLE
Could you pls provide any demo code？ Thx！

### ISSUE THREAD

**Issue by dvlee1024** [cgutman/AdbLib#3]
I try to "adb connect" android device with shell command these days and found that some devices could not be connected successful which display "unauthorized". I guess the reason is using "connect" command  by shell could not get RSA code which is use to get authority.

So I want to use adblib to connect device. Could you pls provide any demo code to use adblib?

**Comment by dvlee1024** [comment]
Thx! I found AdbLibTest.
https://github.com/cgutman/AdbLibTest

**Comment by cgutman** [comment]
Added a link in the readme.
