### ISSUE TITLE
some devices connect failed

### ISSUE THREAD

**Issue by likezjuisee** [cgutman/AdbLib#9]
![image](https://user-images.githubusercontent.com/12730220/61203598-57f0f000-a6da-11e9-8f13-e395c41722ce.png)
Like the image shows, the device is oppo R7 sdk 21.

**Comment by likezjuisee** [comment]
I have solved this problem, forget it.

**Comment by shaikh-amaan-fm** [comment]
> I have solved this problem, forget it.

Can you share some info on how you solved the issue?
